// import { cookies } from "next/headers";
// import AuthInitializer from "@/components/auth/AuthInitializer";
// import Header from "@/components/organisms/Header";


// export default function RootLayout({
      //   children,
      // }: Readonly<{
        //   children: React.ReactNode;
        // }>) {
          //   return (
            //     <html
            //       lang="en"
            //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Header />

//         {children}
        
//         </body>

//     </html>
//   );
// }
// src/app/layout.tsx (서버 컴포넌트)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';
import AuthInitializer from '@/components/auth/AuthInitializer';
import Header from '@/components/organisms/Header';
const apuiurl=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8081";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
    };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 1. 쿠키에서 refreshToken 가져오기 (Next.js 서버 함수)
  const cookieStore = await cookies();
  const refreshToken = cookieStore.get('refreshToken')?.value;

  let authData = {
    userName: null,
    roles: [],
  };

  // 2. 리프레시 토큰이 있다면 백엔드에 새 액세스 토큰 요청 (서버 -> 백엔드)
  if (refreshToken) {
    try {
      // 주의: 백엔드 서버 주소를 직접 호출해야 합니다. (Internal API Call)
      const response = await fetch(`${apuiurl}/auth/refresh`, {
        method: 'POST',
        headers: {
          'Cookie': `refreshToken=${refreshToken}`, // 쿠키 전달
        },
        cache: 'no-store', // 서버에서 매번 새로운 토큰을 가져와야 함
      });

      if (response.ok) {
        const data = await response.json();
        authData = {
          userName: data.user.userName,
          roles: data.user.roles,
        };
      }
    } catch (error) {
      console.error('서버측 인증 복구 실패:', error);
    }
  }

  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        {/* 3. 가져온 정보를 클라이언트 스토어에 주입 (수혈기) */}
        <AuthInitializer 
          userName={authData.userName}
          roles={authData.roles}
        />
        <Header />
        <main className="container mx-auto px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}